### ISSUE TITLE
"Not Exist" error kept shown when deleting the stack

### ISSUE THREAD

**Issue by henrysher** [Kotaimen/awscfncli#89]
When I tried to delete the stack by "cfn-cli -f cfn-cli.yaml stack delete", the error message kept shown: **An error occurred (ValidationError) when calling the DescribeStackEvents operation: Stack [ddb-table] does not exist**

Finally, it succeeded to delete the stack after a while, the error message seems annoying to the SysAdmin.

[Details]
> 
Deleting stack Develop.Table
StackName: ddb-table
Profile: default
Region: cn-north-1
Account: 1XXXXXXXXX74
Identity: arn:aws-cn:iam::1XXXXXXXXX74:user/XXXX
Disabling TerminationProtection
StackID: arn:aws-cn:cloudformation:cn-north-1:1XXXXXXXXX74:stack/ddb-table/8a3a97c0-9cb9-11ea-a937-027b3755dd08
Created: 2020-05-23 05:52:09.100000+00:00
TerminationProtection: False
Drift Status: NOT_CHECKED
05/23/20 05:54:28 - DELETE_IN_PROGRESS - ddb-table(AWS::CloudFormation::Stack) - User Initiated
An error occurred (ValidationError) when calling the DescribeStackEvents operation: Stack [ddb-table] does not exist
Stack delete complete.

**Comment by Kotaimen** [comment]
Hi @henrysher:

Yes this is an annoying behavior due to a design decision: "stack status tailing" part is separated   from "waiting for stack execution complete" (part of the boto3 "waiter" system).
So when stack is already being deleted in CloudFormation service, and the waiter is still waiting that, stack status may report "stack already deleted".
Besides confusing, it really does no harm.

Kotaimen
